### ISSUE TITLE
SystemError: Objects/tupleobject.c:118: bad argument to internal function

### ISSUE THREAD

**Issue by jetmind** [munhitsu/django-dowser#1]
After we installed django-dowser, we started to get strange errors:

```
Traceback (most recent call last):
  File "... site-packages/django/core/handlers/wsgi.py", line 
    from django.conf import settings
SystemError: Objects/tupleobject.c:118: bad argument to internal function
```

On devserver seems like everything is working fine, but when we use uwsgi - we get such error.

This error occurs after a second request to any page.

**Comment by diogobaeder** [comment]
Hi guys,

I just had this issue in an application run with CherryPy and dowser, so it seems to me to be an issue in dowser itself - not `django-dowser`.

I'm not using `django-dowser`, just wanted to let you guys know of the other scenario I'm having this. :-)

Cheers!
