### ISSUE TITLE
Not working in Django 1.3 because of bad import

### ISSUE THREAD

**Issue by ryselis** [munhitsu/django-dowser#11]
django_dowser/urls.py:

name 'patterns' is not defined

This happens because of bad import: `from django.conf.urls import *` works without error but does not import `patterns` because it is in `django.conf.urls.defaults`.

Tested on django 1.3.7

**Comment by munhitsu** [comment]
Hi @ryselis thanks for reporting the importing issue.
I've fixed the urls.py to better cope with imports but it's not gonna make the app compatible fully with Django 1.3.
i.e. the url tag in Django 1.3 expects argument w/o quotes while later versions expect it quoted.
Our aim is to keep it compatible with latest Django version.
https://github.com/munhitsu/django-dowser/commit/b78a3594d305e95f80b7de17fba1c08c71f28c48
