### ISSUE TITLE
Django 1.9 - 'WSGIRequest' object has no attribute 'REQUEST'

### ISSUE THREAD

**Issue by ido777** [munhitsu/django-dowser#12]
When running dowser on Django 1.9.5 I get:

> Traceback (most recent call last):
>   File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "C:\Python27\lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapped_view
>     return view_func(request, *args, **kwargs)
>   File "C:\Python27\lib\site-packages\django_dowser\views.py", line 16, in index
>     floor = request.REQUEST.get('floor', 0)
> AttributeError: 'WSGIRequest' object has no attribute 'REQUEST'

According to Django release notes [see link]( https://docs.djangoproject.com/en/1.9/releases/1.9/#features-removed-in-1-9)
**The WSGIRequest.REQUEST property is removed.**

**Comment by munhitsu** [comment]
Could you test it against the master branch of django-dowser?

**Comment by ido777** [comment]
Well I installed the 0.1.5. version from git 
e.g.
#pip install git+git://github.com/munhitsu/django-dowser.git#
instead of the normal 
pip install django-dowser

and it working :smile: :relieved:

Thanks a lot for your code and for your prompt response :clap:
