### ISSUE TITLE
Project still maintained?

### ISSUE THREAD

**Issue by diogobaeder** [munhitsu/django-dowser#15]
Hi,

I'd like to know if this project is still being maintained; if so, I'd like to make it compatible with Python 3 (currently it's not, it uses Python 2 functions like iteritems or similar). Otherwise I'll fork it and release it with a different name, for Python 3 support.

Thanks!

**Comment by munhitsu** [comment]
Let's try to avoid forking, and I'm delighted with any contribution.
BTW: Think if there are any features that one may need.
